"""empty message

Revision ID: 199898ebe799
Revises: bfbbce90535a
Create Date: 2023-09-12 19:49:11.913001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199898ebe799'
down_revision = 'bfbbce90535a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_constraint('producto_descripcion_key', type_='unique')
        batch_op.drop_constraint('producto_precio_key', type_='unique')
        batch_op.drop_constraint('producto_talla_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.create_unique_constraint('producto_talla_key', ['talla'])
        batch_op.create_unique_constraint('producto_precio_key', ['precio'])
        batch_op.create_unique_constraint('producto_descripcion_key', ['descripcion'])

    # ### end Alembic commands ###
