"""empty message

Revision ID: 6ce3649fca53
Revises: 199898ebe799
Create Date: 2023-09-12 19:50:33.764362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce3649fca53'
down_revision = '199898ebe799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_constraint('producto_nombre_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.create_unique_constraint('producto_nombre_key', ['nombre'])

    # ### end Alembic commands ###
