"""empty message

Revision ID: 8d52a74726ea
Revises: 6248d0a9af3d
Create Date: 2023-09-13 01:28:40.975116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d52a74726ea'
down_revision = '6248d0a9af3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_constraint('cliente_apellido_key', type_='unique')
        batch_op.drop_constraint('cliente_direccion_key', type_='unique')
        batch_op.drop_constraint('cliente_nombre_key', type_='unique')
        batch_op.create_unique_constraint(None, ['email'])

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.String(length=1526), nullable=True))
        batch_op.add_column(sa.Column('cantidad', sa.String(length=80), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['password'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_column('cantidad')
        batch_op.drop_column('imagen')

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('cliente_nombre_key', ['nombre'])
        batch_op.create_unique_constraint('cliente_direccion_key', ['direccion'])
        batch_op.create_unique_constraint('cliente_apellido_key', ['apellido'])

    # ### end Alembic commands ###
